### ISSUE TITLE
`priortise_targets`: track how many phenotypes/celltypes/genes dropped at each step

### ISSUE THREAD

**Issue by bschilder** [neurogenomics/MultiEWCE#6]
This now results a named list, one of which is "report":
```R
res <- MultiEWCE::prioritise_targets()
```

"report" is a recording of how many phenotypes/celltypes/genes remained after each filtering step. 
@NathanSkene This will help us to figure out where phenotypes are getting dropped the most.

![Screenshot 2023-02-07 at 17 53 35](https://user-images.githubusercontent.com/34280215/217327267-0a77928c-0116-4e5a-9ba0-77bed9f0f55d.png)

I've tried expanding the Tier assignments using a combination of Momoko's curated + my automated approaches (described here https://github.com/neurogenomics/MultiEWCE/issues/5), but this still seems to be a step where the most phenotypes are dropped. Not necessarily a problem, just something to be aware of.

**Comment by bschilder** [comment]
Updated version after playing around with automated Tier assignment: #5 
![Screenshot 2023-02-07 at 18 47 06](https://user-images.githubusercontent.com/34280215/217337754-6bd1c67c-a30c-4e87-82cc-d4be5bed9110.png)

**Comment by NathanSkene** [comment]
Worth including this as a table in the paper

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bschilder** [comment]
Could also display as a plot:
![filter](https://user-images.githubusercontent.com/34280215/217393706-7a6a6211-23cb-477a-8acd-1f81766406ba.png)

**Comment by NathanSkene** [comment]
Good idea

How comes “keep onsets” has no effect on number of phenotypes? That’s age of onset of phenotypes?

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by NathanSkene** [comment]
I'd drop the nrows facet

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by NathanSkene** [comment]
If possible, might be good to show how each level of severity reduced the number of phenotypes, with a separate label for "no severity data available"

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bschilder** [comment]
> Good idea How comes “keep onsets” has no effect on number of phenotypes? That’s age of onset of phenotypes? 

It actually reduces is by 60 phenotypes. I'm only removing onsets before birth/congenital.
 
![Screenshot 2023-02-08 at 09 39 26](https://user-images.githubusercontent.com/34280215/217492642-69c24813-dd93-4bd1-8473-1147c9834c2f.png)

> I'd drop the nrows facet

Done.

>If possible, might be good to show how each level of severity reduced the number of phenotypes, with a separate label for "no severity data available"

Would be nice, but I'll have to think about this a bit to figure out how I'd implement it.

**Comment by bschilder** [comment]
@NathanSkene I think this might work:

![tier_proportions](https://user-images.githubusercontent.com/34280215/217520342-9e0ea8a7-4a7c-4aa3-8f87-c7fb14ad4e78.png)
